### ISSUE TITLE
Enabling tests in nix build

### ISSUE THREAD

**Issue by srid** [benwis/benwis_leptos#2]
I see that cargo tests are disabed in nix build:

https://github.com/benwis/benwis_leptos/blob/928ea7e7c20a86be91ad27e75cf297a2fbef681d/flake.nix#L105

Is there a reason why? 

Out of curiosity, I tried building my template with `doCheck` removed, and this is what I saw:

```
++ command cargo test --release
   Compiling leptos-fullstack v0.1.0 (/private/tmp/nix-build-leptos-fullstack-0.1.0.drv-6/source)
error: output file /private/tmp/nix-build-leptos-fullstack-0.1.0.drv-6/source/target/release/deps/libleptos_fullstack.rlib is not writeable -- check its permissions
```

What might be the way to go about allowing running of tests in the Nix build?

**Comment by benwis** [comment]
I think alot of that will depend on what kind of testing your project has. If it's regular cargo tests, then I'm pretty sure you could run `cargo test --features=ssr --release` or similar. You might also have wasm-bindgen tests for the frontend, which would have to be setup differently. I haven't explored that yet, so it's all commented out.


On Tue, Aug 1, 2023, at 2:25 PM, Sridhar Ratnakumar wrote:
> 
> 
> I see that cargo tests are disabed in nix build:
> 
> https://github.com/benwis/benwis_leptos/blob/928ea7e7c20a86be91ad27e75cf297a2fbef681d/flake.nix#L105
> 
> Is there a reason why?
> 
> Out of curiosity, I tried building my template with `doCheck` removed, and this is what I saw:
> 
> `++ command cargo test --release
>    Compiling leptos-fullstack v0.1.0 (/private/tmp/nix-build-leptos-fullstack-0.1.0.drv-6/source)
> error: output file /private/tmp/nix-build-leptos-fullstack-0.1.0.drv-6/source/target/release/deps/libleptos_fullstack.rlib is not writeable -- check its permissions
`

**Comment by srid** [comment]
FYI: Here's what I did 

https://github.com/srid/leptos-fullstack/commit/3e99851d5b821cba979c547adaef5dc56c11770e
